[versions]
paper-api = "1.21.8-R0.1-SNAPSHOT"
lombok = "1.18.34"
shadow = "8.1.8"
run-paper = "3.0.0"
skript = "2.16.1"
itemsadder = "4.0.18-beta-10"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
skript = { group = "com.github.SkriptLang", name = "Skript", version.ref = "skript"}
itemsadder = { group = "beer.devs", name = "itemsadder-api", version.ref = "itemsadder"}

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }
